package threads;

public class ResultTask extends Thread{
    public void run(){
        System.out.println("Result Generated by :"+
        Thread.currentThread().getName());
    }

    public static void main(String[] args) {
        ResultTask r = new ResultTask();
        r.run();
        r.start();
    }
}
